[package]
name = "rust-postgresql-youtube-channel"
version = "0.1.0"
authors = ["Salvador Guzman <guzmansalv@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.2"
scraper = "0.7.0"
serde_json = "1.0.30"
postgres = "0.15.2"
rand = "0.5.5"
influent = "0.4.1"
rayon = "1.0.2"