[package]
name = "rust-postgresql-youtube-channel"
version = "0.1.0"
authors = ["Salvador Guzman <guzmansalv@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.0.2"
tokio = "0.1.8"
reqwest = "0.9.2"